#!/bin/bash
RUNNING=()
for s in $(tmux ls | cut -d: -f1); do
    RUNNING=(${RUNNING[@]} "$s")
done
SESSION=$(echo "${RUNNING[@]}" | tr ' ' '\n' | dmenu $@)

if [[ -n "$SESSION" ]]; then
    for s in ${RUNNING[@]}; do
        if [[ $s = $SESSION ]]; then
            exec urxvt -e tmux att -t "$SESSION"
        fi
    done
    exec urxvt -e tmux new -s "$SESSION"
fi
